<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260831000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Make users global and move tenant access to memberships';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE memberships (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, tenant_id INT NOT NULL, roles JSON NOT NULL, active BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_865A4776A76ED395 ON memberships (user_id)');
        $this->addSql('CREATE INDEX IDX_865A47769033212A ON memberships (tenant_id)');
        $this->addSql('CREATE UNIQUE INDEX membership_user_tenant_unique ON memberships (user_id, tenant_id)');
        $this->addSql("INSERT INTO memberships (user_id, tenant_id, roles, active) SELECT id, tenant_id, '[]'::json, true FROM users");
        $this->addSql('ALTER TABLE memberships ADD CONSTRAINT FK_MEMBERSHIP_USER FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE memberships ADD CONSTRAINT FK_MEMBERSHIP_TENANT FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE users DROP CONSTRAINT FK_1483A5E99033212A');
        $this->addSql('DROP INDEX IDX_1483A5E99033212A');
        $this->addSql('ALTER TABLE users DROP tenant_id');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE users ADD tenant_id INT DEFAULT NULL');
        $this->addSql('UPDATE users SET tenant_id = (SELECT tenant_id FROM memberships WHERE memberships.user_id = users.id ORDER BY id LIMIT 1)');
        $this->addSql('ALTER TABLE users ALTER tenant_id SET NOT NULL');
        $this->addSql('CREATE INDEX IDX_1483A5E99033212A ON users (tenant_id)');
        $this->addSql('ALTER TABLE users ADD CONSTRAINT FK_1483A5E99033212A FOREIGN KEY (tenant_id) REFERENCES tenants (id) NOT DEFERRABLE');
        $this->addSql('DROP TABLE memberships');
    }
}
