<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Synchronizes the historical migrations with the current Doctrine metadata.
 */
final class Version20260731141251 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Synchronize the PostgreSQL schema with Doctrine metadata and add tenant settings';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE tenant_settings (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, setting_key VARCHAR(100) NOT NULL, value TEXT DEFAULT NULL, tenant_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C4E3C2329033212A ON tenant_settings (tenant_id)');
        $this->addSql('CREATE UNIQUE INDEX tenant_setting_unique ON tenant_settings (tenant_id, setting_key)');
        $this->addSql('ALTER TABLE tenant_settings ADD CONSTRAINT FK_C4E3C2329033212A FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE documents ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE documents ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE documents ALTER active DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN documents.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN documents.updated_at IS \'\'');
        $this->addSql('ALTER INDEX idx_a2b07288b03a8386 RENAME TO IDX_A2B072889033212A');
        $this->addSql('ALTER TABLE notifications DROP CONSTRAINT IF EXISTS FK_6000B0D39033212A');
        $this->addSql('ALTER TABLE notifications DROP CONSTRAINT IF EXISTS FK_6000B0D3B03A8386');
        $this->addSql('ALTER TABLE notifications DROP CONSTRAINT IF EXISTS FK_6000B0D3B03A8386_2');
        $this->addSql('ALTER TABLE notifications ADD CONSTRAINT FK_6000B0D39033212A FOREIGN KEY (tenant_id) REFERENCES tenants (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE notifications ADD CONSTRAINT FK_6000B0D3B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE notifications ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE notifications ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE notifications ALTER type DROP DEFAULT');
        $this->addSql('ALTER TABLE notifications ALTER status DROP DEFAULT');
        $this->addSql('ALTER TABLE notifications ALTER send_email DROP DEFAULT');
        $this->addSql('ALTER TABLE notifications ALTER send_in_app DROP DEFAULT');
        $this->addSql('ALTER TABLE notifications ALTER is_read DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN notifications.sent_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN notifications.read_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN notifications.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN notifications.updated_at IS \'\'');
        $this->addSql('ALTER INDEX idx_6000b0d3b03a8386 RENAME TO IDX_6000B0D39033212A');
        $this->addSql('ALTER INDEX idx_6000b0d3b03a8386_2 RENAME TO IDX_6000B0D3B03A8386');
        $this->addSql('ALTER TABLE products ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE products ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN products.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN products.updated_at IS \'\'');
        $this->addSql('ALTER TABLE tenants ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE tenants ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN tenants.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN tenants.updated_at IS \'\'');
        $this->addSql('ALTER TABLE users ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE users ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN users.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN users.updated_at IS \'\'');
        $this->addSql('DROP INDEX idx_75ea56e016ba31db');
        $this->addSql('DROP INDEX idx_75ea56e0fb7336f0');
        $this->addSql('DROP INDEX idx_75ea56e0e3bd61ce');
        $this->addSql('ALTER TABLE messenger_messages ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE messenger_messages ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN messenger_messages.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.available_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.delivered_at IS \'\'');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE tenant_settings DROP CONSTRAINT FK_C4E3C2329033212A');
        $this->addSql('DROP TABLE tenant_settings');
        $this->addSql('ALTER TABLE documents ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE documents ALTER id SET DEFAULT nextval(\'documents_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE documents ALTER active SET DEFAULT true');
        $this->addSql('COMMENT ON COLUMN documents.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN documents.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER INDEX idx_a2b072889033212a RENAME TO idx_a2b07288b03a8386');
        $this->addSql('DROP INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750');
        $this->addSql('ALTER TABLE messenger_messages ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE messenger_messages ALTER id SET DEFAULT nextval(\'messenger_messages_id_seq\'::regclass)');
        $this->addSql('COMMENT ON COLUMN messenger_messages.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.available_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.delivered_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE INDEX idx_75ea56e016ba31db ON messenger_messages (delivered_at)');
        $this->addSql('CREATE INDEX idx_75ea56e0fb7336f0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX idx_75ea56e0e3bd61ce ON messenger_messages (available_at)');
        $this->addSql('ALTER TABLE notifications DROP CONSTRAINT IF EXISTS FK_6000B0D39033212A');
        $this->addSql('ALTER TABLE notifications DROP CONSTRAINT IF EXISTS FK_6000B0D3B03A8386');
        $this->addSql('ALTER TABLE notifications DROP CONSTRAINT IF EXISTS FK_6000B0D3B03A8386_2');
        $this->addSql('ALTER TABLE notifications ADD CONSTRAINT FK_6000B0D3B03A8386 FOREIGN KEY (tenant_id) REFERENCES tenants (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE notifications ADD CONSTRAINT FK_6000B0D3B03A8386_2 FOREIGN KEY (created_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE notifications ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE notifications ALTER id SET DEFAULT nextval(\'notifications_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE notifications ALTER type SET DEFAULT \'info\'');
        $this->addSql('ALTER TABLE notifications ALTER status SET DEFAULT \'pending\'');
        $this->addSql('ALTER TABLE notifications ALTER send_email SET DEFAULT false');
        $this->addSql('ALTER TABLE notifications ALTER send_in_app SET DEFAULT true');
        $this->addSql('ALTER TABLE notifications ALTER is_read SET DEFAULT false');
        $this->addSql('COMMENT ON COLUMN notifications.sent_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN notifications.read_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN notifications.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN notifications.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER INDEX idx_6000b0d3b03a8386 RENAME TO idx_6000b0d3b03a8386_2');
        $this->addSql('ALTER INDEX idx_6000b0d39033212a RENAME TO idx_6000b0d3b03a8386');
        $this->addSql('ALTER TABLE products ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE products ALTER id SET DEFAULT nextval(\'products_id_seq\'::regclass)');
        $this->addSql('COMMENT ON COLUMN products.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN products.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE tenants ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE tenants ALTER id SET DEFAULT nextval(\'tenants_id_seq\'::regclass)');
        $this->addSql('COMMENT ON COLUMN tenants.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN tenants.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE users ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE users ALTER id SET DEFAULT nextval(\'users_id_seq\'::regclass)');
        $this->addSql('COMMENT ON COLUMN users.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN users.updated_at IS \'(DC2Type:datetime_immutable)\'');
    }
}
