services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Fixtures\Messenger\RoutingProbe:
        public: true

    App\Tests\Fixtures\Messenger\MiddlewareExecutionProbe:
        public: true

    App\Tests\Fixtures\Messenger\SynchronousTenantMessageHandler: ~

    App\Tests\Fixtures\Scheduler\SchedulerExecutionProbe:
        public: true

    App\Tests\Fixtures\Scheduler\SchedulerExecutionProbeHandler: ~
